hr_train_dataset:
  dataset:
    name: image-folder
    args:
      root_path:
      # repeat: 20
      repeat: 1
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 64
      scale_max: 4
      augment: true
  # batch_size: 64
  batch_size: 2

hr_val_dataset:
  dataset:
    name: image-folder
    args:
      root_path:
  wrapper:
      name: sr-implicit-downsampled-fast
      args:
        scale_min: 2
        scale_max: 2
  batch_size: 1
  # batch_size: 32
  


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

sr_model:
  name: sronet
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    width: 256
    blocks: 16

optimizer:
  name: adam
  args:
    lr: 4.e-5
    #weight_decay: 1.e-5
epoch_max: 1050
warmup_step_lr:
  multiplier: 10
  total_epoch: 50

epoch_val: 50
epoch_save: 250



